version: "3.8"
services:
  nuxt:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./nuxt/.env:/app/.env:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
