const API_CONST = {
    AUTH: {
        LOGIN: 'admin/login',
        LOGOUT: 'admin/logout',
        REGISTER: 'auth/register',
        VERIFY_OTP_AFTER_LOGIN: 'auth/email/verify-login',
        VERiFY_OTP_AFTER_REGISTER: 'auth/email/verify-register',
        RESEND_VERIFY_EMAIL: 'auth/email/resend-verify-email',
        FORGOT_PASSWORD: 'auth/forgot-password',
        RESET_PASSWORD: 'auth/reset-password',
        SIGN_IN_GOOGLE_URL: 'auth/google-sign-in-url',
        SIGN_IN_CALLBACK: 'auth/google-callback',
        GET_PROFILE: 'admin/get-profile',
        UPDATE_PROFILE: 'admin/update-profile',
        CREATE_USER: 'admin/create-user',
        UPDATE_FCM_TOKEN: 'admin/update-fcm-token',
    },
    QUIZZE: {
        LIST: 'admin/quizzes/list',
        CREATE_QUIZZE: 'admin/quizzes/create',
        DELETE_QUIZZE: 'admin/quizzes/delete',
        LIST_QUESTION: 'admin/quizzes/list-question',
        UPDATE_QUESTION: 'admin/quizzes/update-question',
        CREATE_QUESTION: 'admin/quizzes/create-question',
        DELETE_QUESTION: 'admin/quizzes/delete-question',
        SHARE_QUIZZE: 'admin/quizzes/share',
        DETAIL_SHARE_QUIZZE: 'admin/quizzes/detail-share',
        ACCEPT_SHARE_QUIZZE: 'admin/quizzes/accept-share',
        REJECT_SHARE_QUIZZE: 'admin/quizzes/reject-share',
        SEARCH_QUIZZE: 'admin/quizzes/search',
        SEARCH_BY_KEYWORD: 'admin/quizzes/search-keyword',
    },
    CATEGORY: {
        LIST_CATEGORY: 'admin/category/list',
    },
    ROOM: {
        CREATE: 'admin/room/create',
        CHECK_VALID: 'admin/room/check-valid',
        VERIFY_CODE: 'user/room/verify-code',
        LIST_QUESTION_OF_ROOM: 'user/room/list-question',
        START: 'admin/room/start',
        NEXT_QUESTION: 'admin/room/next-question',
        ADMIN_END_GAME: 'admin/room/end-game',
        GET_DETAIL_ROOM: 'admin/room/detail',
        GET_LIST_ROOM_REPORT: 'admin/room/list-report',
        DELETE_ROOM_REPORT: 'admin/room/delete-report',
    },
    GAMER: {
        CREATE_SETTING: 'user/gamer/create-setting',
        SUBMIT_ANSWER: 'user/gamer/submit-answer',
        OUT_GAME: 'user/gamer/out-game',
        SUBMIT_HOMEWORK: 'user/gamer/submit-homework',
        GET_QUANTITY_GAMER_ANSWER: '/user/gamer/get_quantity_gamer_answer'
    },
    FRONT_END: {
        USER_GAME: '/user/join/game',
        ADMIN_GAME: '/admin/dashboard/activity',
        HOMEWORK: '/user/join/homework',
        REPORT_DETAIL: '/admin/dashboard/reports',
        DETAIL_QUIZ: '/admin/dashboard/my-library',
        USER_DETAIL: '/admin/account',
        SETTING: '/admin/dashboard/settings',
    },
    NOTIFICATION: {
        LIST_NOTIFICATION: 'admin/notification/list',
        DELETE_NOTIFICATION: 'admin/notification/delete',
    },
    USER: {
        LIST_USER: 'admin/user/search',
        DELETE_USER: 'admin/user/delete',
        DISABLE_USER: 'admin/user/disable',
        ACTIVE_USER: 'admin/user/active',
        SEARCH_ELK: 'admin/user/search-elk',
        CHANGE_PASSWORD: 'admin/change-password',
        UPLOAD_IMAGE: 'admin/upload-image',
    },
    DASHBOARD: {
        INDEX: 'admin/dashboard/index',
    },
    SETTING: {
        GET_SETTING: 'admin/setting/index',
        UPDATE_SETTING: 'admin/setting/update',
        GET_LATEST_UPDATE: 'admin/setting/latest-updated',
    },
};

export default API_CONST;
